####
# GitHub Actions file for push and pull_request events
####

# Explanation:
# git log --format=%H -n 1 origin/${{ github.base_ref }}
#
# - with "git log" we print an overview about the history of git
# - with "--format=%H" we get the commit ids
# - with "-n 1" we limit the commit ids to the newest one
#
# Using this on your local machine you will get a commit id that looks something like this:
# 5d7fca10a3f50bf38ffd1f9a56127594db95eb1a
#
# Using this on GitHub it you will get the same id but with quotation marks:
# “5d7fca10a3f50bf38ffd1f9a56127594db95eb1a”
#
# So we need to remove these by using sed -e 's/^“//' -e 's/”$//' <<<"$NX_BASE_TEMP"

name: Feature Branch Workflow

on:
  push:
    branches-ignore:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # Check out the last 2 commits with fetch-depth: 2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Fetch origin
        run: git fetch origin

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests & build
        shell: bash
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            echo "Pull Request Event - GitHub.BaseRef: $GITHUB_BASE_REF"
            export NX_BASE_TEMP=$(git log --format=%H -n 1 origin/${{ github.base_ref }})
            export NX_BASE=$(sed -e 's/^“//' -e 's/”$//' <<<"$NX_BASE_TEMP")
            echo "Pull Request Event - since GitHub.BaseRef was found - using commit id of target branch: $NX_BASE"
          else
            echo "Push Event"
            export NX_BASE=$(git rev-parse HEAD~1)
            echo "Push Event - since GitHub.BaseRef not found - using last commit id: $NX_BASE"
          fi
          npm run nx affected:test -- --base=$NX_BASE
          npm run nx affected:build -- --base=$NX_BASE